version: "3.8"
networks:
    default:
        name: train-primera-network
        external: true
services:
    train-primera:
        image: train-primera
        container_name: train-primera
        privileged: true
        volumes:
            - ../../../secrets/:/secrets
            - ../docker-volumes/training-data/:/app/data
        ports:
            - 8888:8888
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/flavor-fusion-service.json
            GCP_PROJECT: "flavor-fusion"
            GCP_ZONE: "us-central1-a"
            GCS_DATA_BUCKET: "lsars-data"
            GCS_MODEL_BUCKET: "primera-training"
            JUPYTER_ENABLE_LAB: "yes"
            JUPYTER_TOKEN: "docker"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

