version: "3.8"
networks:
    default:
        name: train-primera-network
        external: true
services:
    train-primera:
        image: train-primera
        container_name: train-primera
        volumes:
            - ../../../secrets/:/secrets
            - ../docker-volumes/lsars-data/:/app/data
            - ../docker-volumes/notebooks/:/app/notebooks
        ports:
            - 8888:8888
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/flavor-fusion-service.json
            GCP_PROJECT: "flavor-fusion"
            GCP_ZONE: "us-central1-a"
            GCS_BUCKET_NAME: "lsars-data"
            environment:
            JUPYTER_ENABLE_LAB: "yes"
            JUPYTER_TOKEN: "docker"